### ISSUE TITLE
glob.glob error occured

### ISSUE THREAD

**Issue by PINTO0309** [sleepy-maker/easyGAN#2]
My environment:
Ubuntu 16.04
Python 2.7
pip 18.0
`sudo -H pip install easygan`
Tensorflow-gpu  1.10.1
Geforce GTX 1070

I executed the following command as tutorial.
`$ easygan --folder "puppies" --batch 55`

```
Traceback (most recent call last):
  File "/usr/local/bin/easygan", line 6, in <module>
    easygan.main()
  File "/usr/local/lib/python2.7/dist-packages/easygan/__init__.py", line 250, in main
    run_DCGAN(folder, batch)
  File "/usr/local/lib/python2.7/dist-packages/easygan/__init__.py", line 193, in run_DCGAN
    batch_image = image_batch(filePath, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/easygan/__init__.py", line 140, in image_batch
    files = glob.glob(source_dir + filePath + "/*.png", recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'
```
But, the following was successful.
Edited \_\_init\_\_.py
```
files = glob.glob(source_dir + filePath + "/*.png", recursive=True)
↓
files = glob.glob(source_dir + filePath + "/*.png")
```
\_\_init\_\_.py --> compile --> \_\_init\_\_.pyc

`$ easygan --folder "puppies" --batch 55`

**Comment by sleepy-maker** [comment]
Fixed this issue
v0.2 only python3
v0.3 works with python2 & python3
